/* Laya's training grounds: real progress, real trials, no invented victory curve. */
"use strict";
function learningRounds() { return state.trainingLoop?.rounds || []; }
function learningProofChart(rounds) {
  const measured = [...rounds].reverse().filter(r => r.proof?.delta != null).slice(-12);
  if (!measured.length) return `<div class="trial-empty"><span>${sigil("shield")}</span><h3>The first trial awaits.</h3><p>A round automatically tests the source model and its candidate on the same held-out examples. Their measured scores will appear here.</p></div>`;
  const width=800, height=236, left=48, right=24, top=18, bottom=38;
  const x=i=>left+(i+.5)*(width-left-right)/measured.length, y=v=>top+(1-v)*(height-top-bottom);
  const same = new Set(measured.map(r=>r.proof.benchmark)).size === 1;
  return `<div class="trial-chart"><svg viewBox="0 0 ${width} ${height}" role="img" aria-label="Held-out accuracy from 0 to 100 percent. Each round compares source and candidate on its own benchmark.">${[0,.25,.5,.75,1].map(v=>`<line class="trial-grid" x1="${left}" x2="${width-right}" y1="${y(v)}" y2="${y(v)}"/><text class="trial-axis" x="${left-10}" y="${y(v)+4}" text-anchor="end">${v*100}%</text>`).join("")}${same && measured.length>1 ? ["baseline_accuracy","accuracy"].map((key,i)=>`<polyline class="trial-line ${i ? "candidate" : "source"}" points="${measured.map((r,j)=>`${x(j)},${y(r.proof[key])}`).join(" ")}"/>`).join("") : ""}${measured.map((r,i)=>`<g><title>Round ${r.number}: source ${percent(r.proof.baseline_accuracy)}, candidate ${percent(r.proof.accuracy)}, ${r.proof.validation_questions} held-out answers in ${r.proof.validation_groups} groups</title><line class="trial-pair ${r.proof.delta < 0 ? "regression" : ""}" x1="${x(i)}" x2="${x(i)}" y1="${y(r.proof.baseline_accuracy)}" y2="${y(r.proof.accuracy)}"/><circle class="trial-source" cx="${x(i)}" cy="${y(r.proof.baseline_accuracy)}" r="5"/><circle class="trial-candidate ${r.proof.delta < 0 ? "regression" : ""}" cx="${x(i)}" cy="${y(r.proof.accuracy)}" r="6"/><text class="trial-axis" x="${x(i)}" y="${height-12}" text-anchor="middle">R${r.number}</text></g>`).join("")}</svg><div class="trial-legend"><span><i class="source"></i>Source model</span><span><i class="candidate"></i>Trained candidate</span><small>${same ? "Same held-out benchmark" : "Benchmarks differ · compare the pair within each round"}</small></div></div>`;
}
function trainingLoss(curve = []) {
  if (curve.length<2) return "";
  const min=Math.min(...curve.map(r=>r.loss)),max=Math.max(...curve.map(r=>r.loss)),last=curve.at(-1);
  const y=v=>70-(v-min)/Math.max(.000001,max-min)*52;
  return `<div class="training-loss"><div><span>Training loss · lower is better</span><strong>${last.loss.toFixed(4)}</strong></div><svg viewBox="0 0 600 80" role="img" aria-label="Training loss over optimizer steps, not held-out accuracy"><polyline points="${curve.map((r,i)=>`${8+i/Math.max(1,curve.length-1)*584},${y(r.loss)}`).join(" ")}"/></svg><small>Step ${last.step} · training fit; the independent trial determines improvement</small></div>`;
}
function trainingQuest(compact = false) {
  const a=state.trainingLoop || {enabled:false,rounds:[],approved_answers:state.learning?.labeled_questions || 0,new_answers:0,min_new_answers:10,groups:{train:0,validation:0},state:"paused"};
  const rounds=a.rounds, current=rounds[0], xp=a.approved_answers || 0, level=Math.floor(xp/50)+1;
  const titles=["Rune apprentice","Lesson keeper","Pattern smith","Trial keeper","Lorewright"];
  const title=titles[Math.min(titles.length-1,level-1)];
  const ready = a.groups.train >= 2 && a.groups.validation >= 2;
  const next = !xp ? "Review your first supported decision. There are no approved training examples yet." : !ready ? "Review independent runs until at least two training and two held-out groups remain after data checks." : "Group prerequisites are present; a round still checks dataset quality and runtime availability.";
  if(compact) return `<section class="panel training-invitation"><span class="quest-emblem">${sigil("rune")}</span><div><div class="eyebrow">LAYA’S TRAINING GROUNDS · LEVEL ${level}</div><h3>${title}</h3><p>${esc(next)}</p></div>${button("Enter training grounds →","lab-tab",'data-tab="training"',"primary")}</section>`;
  const busy=a.active_job && active(a.active_job.status), progress=a.active_job?.progress || {};
  const phase=current?.phase || "gather", phaseIndex=["export","baseline","train","evaluate","calibrate","complete"].indexOf(phase);
  const meter=progress.total ? Math.min(100,progress.done/progress.total*100) : 0;
  const selected=rounds.find(r=>r.id === state.learningRound) || rounds.find(r=>r.proof) || current;
  const scores=selected?.proof;
  const controls=`${!ready ? button("Review decisions →", "lab-tab", 'data-tab="review"', "primary") : ""}${button(a.enabled ? "Pause auto-training" : "Enable auto-training", "training-toggle", `data-enabled="${!a.enabled}"`, a.enabled || !ready ? "" : "primary")}${button("Training settings", "training-settings")}${a.state === "needs_attention" ? button("Retry this step →", "training-retry", "", "primary") : ""}`;
  return `<section class="training-grounds"><div class="quest-hero panel ${busy ? "quest-active" : ""}"><div class="quest-copy"><div class="eyebrow">THE LOREKEEPER’S ASCENT</div><h2>${!xp ? "Start with a<br>reviewed lesson." : !ready ? "Build independent<br>teaching evidence." : "Lessons in.<br>Tested outcomes."}</h2><p>${esc(next)} Every round saves its training and evaluation evidence.</p><div class="actions">${controls}</div><div class="quest-automation-state"><i class="${busy ? "live" : ""}"></i><span>${esc(a.reason || "Enable automatic training to begin.")}</span></div></div><div class="quest-level"><div class="quest-rune" aria-hidden="true"><span class="quest-ring"></span><span class="quest-ring ring-two"></span>${sigil("rune")}<span class="quest-star star-a">✦</span><span class="quest-star star-b">✧</span></div><div class="eyebrow">LEVEL ${level} · ${title.toUpperCase()}</div><strong>${xp} <small>knowledge XP</small></strong><div class="quest-xp" role="progressbar" aria-label="Knowledge XP toward next level" aria-valuenow="${xp%50}" aria-valuemin="0" aria-valuemax="50"><i style="width:${xp%50/50*100}%"></i></div><small>1 XP per retained approved answer · ${50-xp%50} to level ${level+1}</small></div></div>
  <div class="quest-milestones">${[["seed",a.groups.train,"training groups"],["shield",a.groups.validation,"held-out groups"],["forge",a.completed_rounds || 0,"completed rounds"],["spark",rounds.filter(r=>r.proof?.outcome === "gain").length,"measured gains"]].map(([icon,n,label])=>`<div>${sigil(icon)}<strong>${n}</strong><span>${label}</span></div>`).join("")}</div>
  <section class="panel quest-round"><div class="panel-header"><div><div class="eyebrow">${current ? `ROUND ${current.number}` : "THE NEXT QUEST"}</div><h3>${current?.status === "complete" ? "The trial is recorded." : busy ? "Laya is at work." : a.state === "needs_attention" ? "A lesson needs attention." : "Growing the next round."}</h3></div>${badge(busy ? "running" : current?.status || a.state)}</div><div class="panel-body"><ol class="quest-stages">${[["export","Gather","scroll"],["baseline","Set the bar","compass"],["train","Forge","forge"],["evaluate","Trial","shield"],["calibrate","Record","rune"]].map(([step,label,icon],i)=>`<li class="${phaseIndex>i ? "done" : phaseIndex===i && current ? "current" : ""}" ${phaseIndex===i ? 'aria-current="step"' : ""}>${sigil(icon)}<span>${label}</span><b>${phaseIndex>i ? "✓" : String(i+1).padStart(2,"0")}</b></li>`).join("")}</ol>${busy ? `<div class="quest-live" aria-live="polite"><div><strong>${esc(progress.message || ({loading:"Loading the local checkpoint",training:"Updating the decision heads",evaluation:"Scoring held-out examples",control:"Testing shuffled-state control"}[progress.phase]) || current.phase)}</strong><span>${progress.total ? `${progress.done} / ${progress.total}` : age(a.active_job.started_at_ms) + " elapsed"}</span></div><div class="quest-live-track ${progress.total ? "" : "indeterminate"}"><i style="width:${meter}%"></i></div>${trainingLoss(progress.loss_curve)}<div class="actions">${button("Live training activity","job",`data-id="${esc(a.active_job.id)}"`,"small")}${button("Stop current job","cancel",`data-id="${esc(a.active_job.id)}"`,"small danger")}</div></div>` : `<p class="help-copy">${esc(current?.error || a.reason || "Waiting for approved examples.")}</p>`}${current?.curation ? `<div class="quest-data-receipt"><strong>${current.curation.retained_examples} distinct examples enter this round</strong><span>${current.curation.duplicate_ids.length} repeated examples removed · ${current.curation.conflicting_ids.length} conflicting examples withheld · original approvals preserved</span></div>` : ""}<p class="help-copy">New or changed answers: ${a.new_answers} / ${a.min_new_answers} for the next round. Runs locally while the control room is running; you can close this tab. Model activation stays in Settings.</p></div></section>
  <section class="panel quest-proof"><div class="panel-header"><div><div class="eyebrow">THE PROVING GROUNDS</div><h3>Show the work. Earn the gain.</h3></div><span class="pill">Held-out accuracy</span></div><div class="panel-body">${learningProofChart(rounds)}${rounds.some(r=>r.proof) ? `<div class="round-picker" role="group" aria-label="Inspect learning round">${rounds.filter(r=>r.proof).slice(0,12).map(r=>`<button class="button small ${selected?.id === r.id ? "primary" : ""}" data-action="learning-round" data-id="${esc(r.id)}" aria-pressed="${selected?.id === r.id}">Round ${r.number} · ${r.proof.delta == null ? "unmeasured" : (r.proof.delta>0 ? "+" : "")+(r.proof.delta*100).toFixed(1)+" pp"}</button>`).join("")}</div>` : ""}${scores ? `<article class="quest-verdict label-live-item" data-live-key="round-${selected.id}-proof"><div class="quest-verdict-score ${scores.outcome}"><strong>${scores.delta == null ? "Unproven" : (scores.delta>0 ? "+" : "")+(scores.delta*100).toFixed(1)+" pp"}</strong><span>${({gain:"Measured gain",regression:"Regression recorded",flat:"No accuracy gain",unmeasured:"More evidence needed"}[scores.outcome])} · round ${selected.number}</span></div><div class="quest-score-grid">${[["Source",scores.baseline_accuracy],["Candidate",scores.accuracy],["Shuffled state",scores.control_accuracy],["Majority baseline",scores.majority_accuracy]].map(([label,v])=>`<div><span>${label}</span><strong>${percent(v)}</strong></div>`).join("")}</div><p>${scores.validation_questions ?? 0} held-out answers · ${scores.validation_groups ?? 0} independent groups · ${scores.qualified_buckets} qualified calibration buckets</p><ul class="help-copy">${scores.notes.map(n=>`<li>${esc(n)}</li>`).join("")}</ul><details data-disclosure-key="round-proof-${esc(selected.id)}"><summary>Inspect benchmark, lineage &amp; jobs</summary><p class="mono">Benchmark ${esc(scores.benchmark || "unavailable")}</p><div class="actions">${Object.entries(selected.jobs).map(([phase,id])=>button(phase,"job",`data-id="${esc(id)}"`,"small")).join("")}</div>${trainingLoss(selected.results?.train?.loss_curve)}<p class="help-copy">${esc(selected.results?.train?.method || "")}</p></details></article>` : ""}</div></section></section>`;
}
function openTrainingSettings() {
  const a=state.trainingLoop || {};
  modal("Tend the training grounds", "Approved evidence starts the next round. One local learning job at a time.", `<form id="training-loop-form"><label class="check-field"><input type="checkbox" name="enabled" ${a.enabled ? "checked" : ""}> Automatically export, train, evaluate, and calibrate candidates</label><div class="field"><label for="training-new-answers">New or changed approved answers per round</label><input id="training-new-answers" name="min_new_answers" type="number" min="1" max="10000" value="${a.min_new_answers || 10}" required><small>A trigger for fresh evidence, not a daily cap. The first eligible round starts immediately.</small></div><p class="help-copy">Uses the local Laya runtime. Identical inputs are deduplicated, preferring their held-out copy; conflicting inputs are withheld. At least two training and two held-out workflow groups must remain. Pausing prevents subsequent steps; an active job can finish. Active model and routing settings remain under your control.</p><button class="button primary" type="submit">Save training settings</button></form>`, "training-loop");
}
