// Gated fake workers let us observe each phase without any paid calls.
const {chromium,expect}=require('@playwright/test');
const {spawn}=require('node:child_process');
const fs=require('node:fs'),path=require('node:path');
(async()=>{
  const fixture=spawn('python3',['-u',path.join(__dirname,'ui_browser_fixture.py')],{env:{...process.env,PYTHONDONTWRITEBYTECODE:'1',FUSION_FIXTURE_COUNCIL:'1',FUSION_FIXTURE_LIVE_COUNCIL:'1'}});
  let browser,page,info,stderr=''; fixture.stderr.on('data',b=>stderr+=b);
  try {
    info=await new Promise((resolve,reject)=>{let out='';const timer=setTimeout(()=>reject(Error('Fixture timeout '+stderr)),20000);fixture.stdout.on('data',b=>{out+=b;const line=out.split('\n').find(l=>l.startsWith('{"url"'));if(line){clearTimeout(timer);resolve(JSON.parse(line));}});fixture.on('exit',c=>{clearTimeout(timer);reject(Error('Fixture exit '+c+' '+stderr));});});
    const release=a=>fs.writeFileSync(path.join(info.root,'release-'+a),'go');
    const eventPath=path.join(info.workspace,'.fusion/decisions/events.jsonl');
    const events=()=>fs.readFileSync(eventPath,'utf8').trim().split('\n').map(JSON.parse);
    const labels=()=>events().filter(e=>e.event==='label');
    const newDecision=(id,summary)=>fs.appendFileSync(eventPath,JSON.stringify({...events().find(e=>e.id==='fixture-decision'&&e.event==='decision'),id,time_ms:Date.now(),state:JSON.stringify({summary})})+'\n');
    browser=await chromium.launch({headless:true});
    page=await browser.newPage({viewport:{width:1440,height:1050}});
    const errors=[];page.on('pageerror',e=>errors.push(e.message));
    const tab = name => page.getByRole('tab',{name:new RegExp('^'+name)}).click();
    await page.goto(info.url);
    await page.locator('nav [data-view=decisions]').click();
    await tab('Garden');
    await page.getByRole('button',{name:'Enable auto-drafts',exact:true}).click();
    await page.locator('#garden-form [name=enabled]').check();
    await page.selectOption('#garden-mode','council');
    await expect(page.locator('#garden-approval')).toHaveValue('human');
    await page.selectOption('#garden-approval','council');
    await page.locator('#garden-form [name=include_existing]').check();
    await page.getByRole('button',{name:'Save garden settings'}).click();
    let live=page.locator('#garden-live-region');
    await expect(live).toContainText('Council in session',{timeout:15000});
    await expect(live.locator('.live-member.running')).toContainText('codex');
    await expect(live).toContainText('Checking the original evidence independently.');
    expect(labels()).toHaveLength(0);
    await live.getByRole('button',{name:'Inspect this decision →'}).click();
    live=page.locator('#label-live-region');
    await expect(page.locator('#label-mode')).toHaveValue('council');
    await expect(page.locator('#label-approval')).toHaveValue('council');
    await page.locator('#label-evidence').fill('My unsaved review notes stay here.');
    await page.evaluate(()=>{window.liveAnimations=[];const original=Element.prototype.animate;Element.prototype.animate=function(frames,options){if(this.classList.contains('label-live-item'))window.liveAnimations.push(this.dataset.liveKey);return original.call(this,frames,options);};});
    release('codex');
    await expect(live.locator('.live-member.success')).toContainText('codex',{timeout:10000});
    await expect(live.locator('.live-member.running')).toContainText('claude');
    await expect(live.locator('.live-votes')).toContainText('false');
    await expect(page.locator('#label-evidence')).toHaveValue('My unsaved review notes stay here.');
    expect(await page.evaluate(()=>window.liveAnimations.some(k=>k.endsWith('codex:success')))).toBe(true);
    expect(labels()).toHaveLength(0);
    await page.evaluate(()=>ORCAppearance.set({theme:'ocean',mode:'light'}));
    await live.screenshot({path:'/tmp/orc-council-live-light.png'});
    await page.evaluate(()=>ORCAppearance.set({theme:'sand',mode:'dark'}));
    await live.screenshot({path:'/tmp/orc-council-live-dark.png'});
    await page.setViewportSize({width:390,height:844});
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
    await live.screenshot({path:'/tmp/orc-council-live-mobile.png'});
    await page.setViewportSize({width:1440,height:1050});
    await page.emulateMedia({reducedMotion:'reduce'});
    await page.evaluate(()=>window.liveAnimations=[]);
    release('claude');
    await expect(live).toContainText('Council approval complete',{timeout:10000});
    expect(await page.evaluate(()=>window.liveAnimations)).toEqual([]);
    expect(labels()).toHaveLength(1);
    expect(labels()[0].source).toBe('council_approved_suggestion');
    await expect(page.locator('#label-evidence')).toHaveValue('My unsaved review notes stay here.');
    await page.locator('#label-evidence').blur();
    await tab('Quality');
    await expect(page.locator('.quality-panel')).toContainText('Council approved automatically');
    await tab('Review');
    await page.reload();
    await expect(live).toContainText('Council approval complete');
    await expect(page.getByRole('button',{name:'Save label changes',exact:true})).toBeDisabled();
    await expect(page.locator('.review-form')).not.toContainText('Waiting for human approval');
    await tab('Overview');
    await expect(page.locator('.learning-growth strong')).toHaveText('1');
    await tab('Garden');
    live=page.locator('#garden-live-region');
    await page.getByRole('button',{name:'Garden settings',exact:true}).click();
    await expect(page.locator('#garden-approval')).toHaveValue('council');
    await page.getByRole('button',{name:'Close dialog'}).click();
    const jobsDir=path.join(info.workspace,'.fusion/ui/jobs');
    const jobs=()=>fs.readdirSync(jobsDir).map(id=>JSON.parse(fs.readFileSync(path.join(jobsDir,id,'job.json')))).filter(j=>j.action==='suggest-labels');
    expect(jobs()).toHaveLength(1);
    expect(jobs()[0].garden_policy).toBeTruthy();
    newDecision('disputed','fixture disputed');
    await expect(live).toContainText('Ready for your review',{timeout:15000});
    await expect(live.locator('.live-votes')).toContainText('true');
    await expect(live.locator('.live-votes')).toContainText('false');
    await expect(page.locator('.garden-panel h2')).toHaveText('1 draft is ready to review.');
    expect(labels()).toHaveLength(1);
    await page.getByRole('button',{name:'Pause garden',exact:true}).click();
    await expect(page.locator('.garden-panel .pill')).toHaveText('paused');
    const exportPath=path.join(info.workspace,'.fusion/ui/jobs');
    await tab('Training');
    await page.getByRole('button',{name:'Export approved labels',exact:true}).click();
    await page.getByRole('button',{name:'Start learning job →',exact:true}).click();
    await expect(page.locator('#job-content .status')).toHaveText('success',{timeout:10000});
    const exported=fs.readdirSync(exportPath).map(id=>path.join(exportPath,id,'dataset.jsonl')).filter(f=>fs.existsSync(f));
    const dataset=JSON.parse(fs.readFileSync(exported.at(-1),'utf8').trim());
    expect(dataset.label_provenance.plausible.source).toBe('council_approved_suggestion');
    expect(dataset.labels).toEqual({plausible:'false'});
    expect(errors).toEqual([]);
    console.log('Council approval browser passed: explicit opt-in, live worker updates/votes, focus preservation, arrival animation/reduced motion, light/dark/mobile, approval provenance/export, persistence, disagreement review and no repeat jobs.');
  }catch(e){if(page)await page.screenshot({path:'/tmp/orc-council-approval-failure.png',fullPage:true}).catch(()=>{});throw e;}
  finally{if(info){for(const a of ['codex','claude'])fs.writeFileSync(path.join(info.root,'release-'+a),'go');}if(browser)await browser.close();fixture.kill('SIGINT');await new Promise(resolve=>{if(fixture.exitCode!==null)return resolve();fixture.once('exit',resolve);setTimeout(resolve,10000).unref();});if(stderr)process.stderr.write(stderr);}
})().catch(e=>{console.error(e);process.exitCode=1;});
