const {chromium, expect} = require('@playwright/test');
const {spawn} = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');
(async () => {
  const fixture=spawn('python3',['-u',path.join(__dirname,'truffle_browser_fixture.py')],{env:{...process.env,PYTHONDONTWRITEBYTECODE:'1',SURVEY_BROWSER:'1'}});
  let browser, stderr='';
  fixture.stderr.on('data',b=>stderr+=b);
  try {
    const info=await new Promise((resolve,reject)=>{
      let output=''; const timeout=setTimeout(()=>reject(Error('Fixture timeout '+stderr)),20000);
      fixture.stdout.on('data',b=>{output+=b;const line=output.split('\n').find(l=>l.startsWith('{"url"'));if(line){clearTimeout(timeout);resolve(JSON.parse(line));}});
      fixture.on('exit',code=>{clearTimeout(timeout);reject(Error('Fixture exited '+code+' '+stderr));});
    });
    browser=await chromium.launch({headless:true});
    const page=await browser.newPage({viewport:{width:1500,height:1050}});
    const errors=[]; page.on('pageerror',e=>errors.push(e.message));
    await page.goto(info.url);
    await page.locator('.nav-item[data-view=truffle]').click();
    await page.getByRole('button',{name:'Map every open issue',exact:true}).click();
    await page.getByRole('button',{name:'Unroll the map →'}).click();
    await expect(page.locator('.forest-metrics')).toContainText('19 open issues mapped',{timeout:20000});
    await expect(page.locator('.forest-patch')).toHaveCount(2);
    await expect(page.locator('.forest-legend .grade-U')).toContainText('Unassessed');
    expect(await page.evaluate(()=>window.PWNED)).toBeUndefined();
    expect(fs.existsSync(path.join(info.workspace,'.fusion/runs'))).toBe(false);
    await page.getByRole('button',{name:'Grade all issues →',exact:true}).click();
    await page.getByRole('button',{name:'Start grading →'}).click();
    await expect(page.locator('#survey-message')).toContainText('Snout is grading',{timeout:20000});
    await expect(page.locator('.forest-metrics')).toContainText('9 / 17',{timeout:20000});
    await expect(page.locator('.forest-legend')).toContainText('Ripe');
    await expect(page.locator('#survey-message')).toContainText('Every issue assessed',{timeout:30000});
    await expect(page.locator('.forest-metrics')).toContainText('17 / 17');
    await page.getByRole('button',{name:'Explore patch →'}).first().click();
    await expect(page.locator('.forest-row')).toHaveCount(3);
    const patchURL=page.url(); expect(patchURL).toContain('patch=1');
    await page.reload(); await expect(page.locator('.forest-row')).toHaveCount(3); expect(page.url()).toBe(patchURL);
    await page.locator('.forest-row-title').filter({hasText:'#2'}).click();
    await expect(page.locator('.forest-issue-detail')).toContainText('app.txt:1');
    await expect(page.locator('.forest-issue-detail')).toContainText('Verification commands');
    await page.locator('#dialog').getByRole('checkbox',{name:'Select issue 2',exact:true}).check();
    await page.locator('[data-action=close]').click();
    await expect(page.locator('#forest-basket-count')).toHaveText('1');
    await page.getByRole('button',{name:'Clear filters',exact:true}).click();
    await page.locator('#forest-grade').selectOption('A');
    await expect(page.locator('.forest-row')).toHaveCount(5);
    await page.locator('#forest-search').fill('Preserve typed');
    await expect(page.locator('.forest-row')).toHaveCount(1);
    expect(page.url()).toContain('q=Preserve+typed');
    await page.reload(); await expect(page.locator('.forest-row')).toHaveCount(1);
    expect(await page.evaluate(()=>window.PWNED)).toBeUndefined();
    await page.getByRole('button',{name:'Clear filters',exact:true}).click();
    await page.getByRole('tab',{name:'Woodland',exact:true}).click();
    await page.evaluate(()=>ORCAppearance.set({theme:'sand',mode:'dark'}));
    await page.screenshot({path:'/tmp/orc-woodland-dark.png',fullPage:true,animations:'disabled'});
    await page.evaluate(()=>ORCAppearance.set({theme:'ocean',mode:'light'}));
    await page.screenshot({path:'/tmp/orc-woodland-light.png',fullPage:true,animations:'disabled'});
    await page.emulateMedia({reducedMotion:'reduce'});
    expect(await page.locator('.forest-snout').evaluate(el=>getComputedStyle(el).animationName)).toBe('none');
    await page.setViewportSize({width:390,height:844});
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
    await page.screenshot({path:'/tmp/orc-woodland-mobile.png',fullPage:true,animations:'disabled'});
    await page.setViewportSize({width:1500,height:1050});
    // Reload starts an empty survey basket, so selecting remains intentional.
    await page.locator('[data-action=forest-issue][data-number="2"]').click();
    await page.locator('#dialog').getByRole('checkbox',{name:'Select issue 2',exact:true}).check();
    await page.locator('[data-action=close]').click();
    await page.getByRole('button',{name:'Queue selected fixes →',exact:true}).click();
    await page.locator('#truffle-queue-form [name=allow_write]').check();
    await page.getByRole('button',{name:'Start issue queue →'}).click();
    await expect(page.locator('#job-content .status')).not.toHaveText(/queued|running/,{timeout:40000});
    if(await page.locator('#job-content .status').textContent()!=='success') throw Error(await page.locator('#job-content').textContent());
    await page.getByRole('button',{name:'Open hunt →'}).click();
    await page.locator('[data-action=forest-issue][data-number="2"]').click();
    await expect(page.getByRole('button',{name:'Open workflow →',exact:true})).toBeVisible();
    expect(fs.readFileSync(path.join(info.workspace,'app.txt'),'utf8')).toBe('before\n');
    expect(errors).toEqual([]);
    console.log('Woodland browser passed: full paginated sync without workers, live batch grades, linked patches, evidence, basket, URL filters/reload, escaped titles, themes, mobile, reduced motion and isolated reviewed implementation.');
  } finally {
    if(browser) await browser.close();
    fixture.kill('SIGINT');
    await new Promise(resolve=>fixture.once('exit',resolve));
  }
})().catch(e=>{console.error(e);process.exitCode=1;});
