const {chromium, expect} = require('@playwright/test');
const {spawn} = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');
(async () => {
  const fixture=spawn('python3',['-u',path.join(__dirname,'truffle_browser_fixture.py')],{env:{...process.env,PYTHONDONTWRITEBYTECODE:'1'}});
  let browser, stderr='';
  fixture.stderr.on('data',b=>stderr+=b);
  try {
    const info=await new Promise((resolve,reject)=>{
      let output='';
      const timeout=setTimeout(()=>reject(Error('Fixture timeout '+stderr)),20000);
      fixture.stdout.on('data',b=>{output+=b;const line=output.split('\n').find(l=>l.startsWith('{"url"'));if(line){clearTimeout(timeout);resolve(JSON.parse(line));}});
      fixture.on('exit',code=>{clearTimeout(timeout);reject(Error('Fixture exited '+code+' '+stderr));});
    });
    browser=await chromium.launch({headless:true});
    const page=await browser.newPage({viewport:{width:1440,height:1050}});
    const errors=[]; page.on('pageerror',e=>errors.push(e.message));
    await page.goto(info.url);
    await page.locator('[data-template=truffle]').click();
    await page.locator('#hunt-count').fill('3');
    await page.getByRole('button',{name:'Find the truffles →'}).click();
    await expect(page.locator('#job-content .status')).toHaveText('success',{timeout:20000});
    await page.getByRole('button',{name:'Open hunt →'}).click();
    await expect(page.locator('.truffle-candidate')).toHaveCount(2);
    await expect(page.locator('.snout-field')).toContainText('Small tusks. Excellent instincts.');
    await expect(page.locator('.truffle-stats')).toContainText('2 / 3');
    expect(await page.evaluate(()=>window.PWNED)).toBeUndefined();
    await page.locator('.truffle-skips > summary').click();
    await expect(page.locator('.truffle-skips')).toContainText('Already assigned');
    await expect(page.locator('.truffle-skips')).toContainText('Unclear reproduction');
    await page.locator('.truffle-candidate details > summary').first().click();
    await expect(page.locator('.truffle-source').first()).toContainText('app.txt:1');
    await page.getByRole('checkbox',{name:'Select issue 2'}).uncheck();
    await page.evaluate(()=>refresh(true));
    await expect(page.getByRole('checkbox',{name:'Select issue 2'})).not.toBeChecked();
    await expect(page.locator('.truffle-candidate details').first()).toHaveAttribute('open','');
    await page.evaluate(()=>ORCAppearance.set({theme:'sand',mode:'dark'}));
    await page.screenshot({path:'/tmp/orc-truffle-dark.png',fullPage:true});
    await page.evaluate(()=>ORCAppearance.set({theme:'ocean',mode:'light'}));
    await page.screenshot({path:'/tmp/orc-truffle-light.png',fullPage:true});
    await page.setViewportSize({width:390,height:844});
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
    await page.screenshot({path:'/tmp/orc-truffle-mobile.png',fullPage:true});
    await page.setViewportSize({width:1440,height:1050});
    await page.getByRole('checkbox',{name:'Select issue 2'}).check();
    await page.getByRole('button',{name:'Queue selected fixes →'}).click();
    await expect(page.locator('#truffle-publish-mode')).toHaveValue('manual');
    await expect(page.locator('#truffle-publish-mode option[value=off]')).toHaveCount(0);
    await page.locator('#truffle-publish-mode').selectOption('auto');
    await page.getByRole('button',{name:'Start issue queue →'}).click();
    expect(JSON.parse(fs.readFileSync(path.join(info.root,'github.json'))).prs).toHaveLength(0);
    await page.locator('#truffle-queue-form [name=allow_write]').check();
    await page.getByRole('button',{name:'Start issue queue →'}).click();
    await expect(page.locator('#job-content .status')).not.toHaveText(/queued|running/,{timeout:40000});
    if (await page.locator('#job-content .status').textContent() !== 'success') throw Error(await page.locator('#job-content').textContent());
    await page.getByRole('button',{name:'Open hunt →'}).click();
    await expect(page.locator('.truffle-stats')).toContainText('2Fixes accepted');
    await expect(page.locator('.snout-trail [aria-current]')).toContainText('Harvest');
    await expect(page.getByRole('link',{name:'View pull request ↗'})).toHaveCount(2);
    const github=JSON.parse(fs.readFileSync(path.join(info.root,'github.json')));
    expect(github.prs).toHaveLength(2);
    expect(github.prs.every(p=>p.baseRefName==='staging'&&p.isDraft&&p.body.includes('Fixes https://github.com/fixture/project/issues/'))).toBe(true);
    expect(new Set(github.prs.map(p=>p.headRefName)).size).toBe(2);
    expect(fs.readFileSync(path.join(info.workspace,'app.txt'),'utf8')).toBe('before\n');
    const huntURL=page.url();
    await page.reload();
    await expect(page.locator('.truffle-candidate')).toHaveCount(2);
    expect(page.url()).toBe(huntURL);
    await page.getByRole('button',{name:'Queue selected fixes →'}).click();
    await page.locator('#truffle-queue-form [name=allow_write]').check();
    await page.getByRole('button',{name:'Start issue queue →'}).click();
    await expect(page.locator('#job-content .status')).toHaveText('success',{timeout:15000});
    expect(JSON.parse(fs.readFileSync(path.join(info.root,'github.json'))).prs).toHaveLength(2);
    expect(errors).toEqual([]);
    console.log('Truffle pig browser passed: real hunt, shortfall/skips, evidence, persistent selection, XSS, themes/mobile, two isolated reviewed PRs, reload and no duplicate work.');
  } finally {
    if(browser) await browser.close();
    fixture.kill('SIGINT');
    await new Promise(resolve=>fixture.once('exit',resolve));
  }
})().catch(e=>{console.error(e);process.exitCode=1;});
