#!/usr/bin/env python3
"""Generate the Fusion CLI and MCP references from their runtime definitions."""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

import fusion_core  # noqa: E402


class ReferenceFormatter(argparse.HelpFormatter):
    def __init__(self, prog):
        # Do not let the caller's terminal width change committed output.
        super().__init__(prog, width=88, max_help_position=26)


def commands(parser, path="fusion", summary=""):
    """Walk choices, including aliases and commands hidden from top-level help."""
    yield path, parser, summary
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            summaries = {entry.dest: entry.help for entry in action._choices_actions}
            for name, child in action.choices.items():
                yield from commands(child, f"{path} {name}", summaries.get(name, ""))


def anchor(name):
    return name.replace(" ", "-")


def cli_document():
    rows = list(commands(fusion_core.build_parser()))
    lines = ["# Fusion CLI reference", "",
             "Generated by `python3 scripts/gen_docs.py` from `fusion_core.build_parser()`.",
             "Do not edit by hand. [Start here](../README.md) · [MCP reference](mcp.md).", "",
             "Global flags normally precede the subcommand. `usage` also accepts `--json`",
             "after its name. Aliases and hidden subcommands are included below.", "",
             "## Commands", ""]
    lines += [f"- [{path}](#{anchor(path)})" for path, _, _ in rows]
    for path, parser, summary in rows:
        parser.formatter_class = ReferenceFormatter
        parser.prog = path
        lines += ["", f"## {path}", ""]
        if summary and summary != argparse.SUPPRESS:
            lines += [summary, ""]
        lines += ["```text", parser.format_help().rstrip(), "```"]
    return "\n".join(lines) + "\n"


def mcp_document():
    definitions = fusion_core.tool_definitions()
    lines = ["# Fusion MCP reference", "",
             "Generated by `python3 scripts/gen_docs.py` from `fusion_core.tool_definitions()`.",
             "Do not edit by hand. [Start here](../README.md) · [Connection guide](workflows.md#driving-orc-from-a-chat-client-mcp).", "",
             "Run `fusion --workspace /absolute/path/to/repository mcp-serve` as a stdio",
             "server. The schemas below preserve required fields, defaults, enums and",
             "nested constraints; omission of a default does not imply one.", "",
             "## Progress and timeouts", "",
             "For a long `tools/call`, set `params._meta.progressToken` to a string or",
             "number (including `0`). While work is active, the shared CLI heartbeat",
             "emits `notifications/progress` about every 10 seconds, with that token,",
             "`progress` equal to elapsed request seconds, and a `message` containing",
             "the current activity and latest public worker event. Notifications are",
             "flushed as JSON-RPC lines before the final response. Without a token,",
             "no progress notifications are sent. Clients must support progress-based",
             "timeout renewal for these notifications to extend their request deadline.", "",
             "`fusion_delegate.timeout_seconds` overrides the configured worker timeout",
             "for one call: an integer from 60 through 14400 seconds. Omit it to use",
             "the config default (`timeout_seconds`, normally 3600). The effective value",
             "is recorded in the run's `task.json` and `result.json`. The CLI equivalent",
             "is `fusion delegate --timeout SECONDS`. This worker limit is independent",
             "of the client's request deadline. `fusion_run_start` returns immediately;",
             "poll `fusion_run_status` for asynchronous workflows.", "",
             "## Tools", ""]
    lines += [f"- [{tool['name']}](#{anchor(tool['name'])})" for tool in definitions]
    for tool in definitions:
        lines += ["", f"## {tool['name']}", "", tool["description"], "",
                  "### Input fields", "", "```json",
                  json.dumps(tool["inputSchema"], indent=2, ensure_ascii=False, sort_keys=True), "```"]
    return "\n".join(lines) + "\n"


def documents():
    return {"cli.md": cli_document(), "mcp.md": mcp_document()}


def sync_docs(directory, check=False):
    stale = []
    for name, content in documents().items():
        path = directory / name
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            stale.append(name)
            if not check:
                directory.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding="utf-8")
    return stale


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="exit nonzero if either reference is missing or stale")
    args = parser.parse_args(argv)
    stale = sync_docs(ROOT / "docs", check=args.check)
    if args.check and stale:
        print("Stale generated documentation: " + ", ".join("docs/" + name for name in stale), file=sys.stderr)
        print("Run python3 scripts/gen_docs.py", file=sys.stderr)
        return 1
    print("Generated references are current." if args.check else "Wrote docs/cli.md and docs/mcp.md.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
